"use client"

import Link from "next/link"
import { useEffect, useState } from "react"
import { Activity, ArrowDownToLine, ArrowLeftRight, ArrowUpFromLine, BarChart3, CircleDollarSign, ClipboardList, Database, FileClock, LayoutDashboard, Network, Receipt, ShieldAlert, Store, Users, WalletCards, Menu, X, MessageSquare, type LucideIcon } from "lucide-react"

const modules: { label: string; href: string; icon: LucideIcon; description: string }[] = [
  ["Overview", "/admin/overview", LayoutDashboard, "Live operations summary"], ["Orders", "/admin/orders", ClipboardList, "Trading order queue"], ["Allocations", "/admin/allocations", Network, "Autopilot allocations"], ["Users & affiliates", "/admin/users", Users, "Customers and referrals"], ["Wallets", "/admin/wallets", WalletCards, "Balances and holds"], ["Deposits", "/admin/deposits", ArrowDownToLine, "Funding review"], ["Withdrawals", "/admin/withdrawals", ArrowUpFromLine, "Payout operations"], ["Transfers", "/admin/transfers", ArrowLeftRight, "Internal movement"], ["Payments", "/admin/payments", Receipt, "Provider payments"], ["Audit log", "/admin/audit-log", FileClock, "Staff actions"], ["Market data", "/admin/market-data", BarChart3, "Prices and feeds"], ["Risk", "/admin/risk", ShieldAlert, "Limits and controls"], ["Data purchases", "/admin/data-purchases", Database, "Airtime and data"], ["Merchant approvals", "/admin/merchants", Store, "Merchant operations"], ["P2P monitor", "/admin/p2p", CircleDollarSign, "Marketplace activity"], ["Support", "/admin/support", MessageSquare, "Customer conversations"]]

export default function AdminDashboard() {
  const [email, setEmail] = useState(""); const [menu, setMenu] = useState(false); const [error, setError] = useState(""); const [counts, setCounts] = useState<Record<string, number>>({})
  useEffect(() => { let active = true; const load = async () => { try { const response = await fetch("/api/admin/requests", { cache: "no-store" }); const payload = await response.json(); const value = String(payload?.user?.email || payload?.email || "").toLowerCase(); if (active && value) setEmail(value); if (active) setCounts({ users: payload.users?.length || 0, orders: payload.orders?.length || 0, deposits: payload.deposits?.length || 0, withdrawals: payload.withdrawals?.length || 0 }) } catch { if (active) setError("Please sign in with an approved staff account.") } }; load(); const timer = window.setInterval(load, 10000); return () => { active = false; window.clearInterval(timer) } }, [])
  const links = <div className="grid grid-cols-2 gap-2 sm:grid-cols-3 md:grid-cols-4">{modules.map(([label, href, Icon, description]) => <Link key={href} href={href} onClick={() => setMenu(false)} className="flex min-h-[106px] flex-col justify-between rounded-2xl border border-[#29413A] bg-[#15231F] p-3 transition hover:border-[#55D6A7] hover:bg-[#1B3029] active:scale-[.98]"><Icon size={19} className="text-[#55D6A7]" aria-hidden="true"/><span><span className="block text-[11px] font-bold leading-4 text-[#EAF4F0]">{label}</span><span className="mt-1 block text-[10px] leading-4 text-[#8CB4A8]">{description}</span></span></Link>)}</div>
  if (error) return <main className="flex min-h-screen items-center justify-center bg-[#101A18] p-5 text-[#EAF4F0]"><div className="w-full max-w-sm rounded-3xl border border-[#713B3B] bg-[#321E20] p-6 text-center"><ShieldAlert className="mx-auto mb-3 text-[#FFB4B4]" size={28}/><h1 className="text-xl font-black">Staff sign-in required</h1><p className="mt-2 text-sm leading-6 text-[#FFB4B4]">Use an approved staff account to access operations.</p><Link href="/auth/login?redirectedFrom=%2Fadmin" className="mt-5 block rounded-xl bg-[#55D6A7] px-4 py-3 text-sm font-black text-[#102019]">Open staff sign-in</Link></div></main>
  return <main className="min-h-screen bg-[#101A18] p-3 text-[#EAF4F0] md:p-8"><div className="mx-auto max-w-6xl"><header className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><button aria-label="Open admin navigation" onClick={() => setMenu(true)} className="rounded-xl border border-[#29413A] p-2 md:hidden"><Menu size={20}/></button><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#8CB4A8]">nexMonie operations</p><h1 className="text-xl font-black md:text-3xl">Affiliate control center</h1></div></div><span className="hidden max-w-56 truncate rounded-full border border-[#29413A] px-3 py-2 text-[10px] text-[#8CB4A8] md:block">{email || "Supabase live"}</span></header><section className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4">{[["Users", counts.users || 0, "/admin/users"], ["Orders", counts.orders || 0, "/admin/orders"], ["Deposits", counts.deposits || 0, "/admin/deposits"], ["Withdrawals", counts.withdrawals || 0, "/admin/withdrawals"]].map(([label, value, href]) => <Link key={String(label)} href={String(href)} className="rounded-2xl border border-[#29413A] bg-[#15231F] p-3"><p className="text-[10px] text-[#8CB4A8]">{label}</p><p className="mt-2 text-xl font-black">{String(value)}</p><p className="mt-1 text-[10px] text-[#55D6A7]">Live from Supabase</p></Link>)}</section><section className="mt-4 rounded-3xl border border-[#29413A] bg-[#15231F] p-3 md:p-6"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#55D6A7]">All admin areas</p><p className="mt-1 text-xs text-[#9BB8AF]">Tap any module. Data refreshes automatically.</p></div><span className="flex items-center gap-1 text-[10px] text-[#55D6A7]"><Activity size={12}/> Live</span></div>{links}</section>{menu && <div className="fixed inset-0 z-40 overflow-y-auto bg-[#101A18] p-3 md:hidden"><div className="mb-4 flex items-center justify-between"><b>Admin navigation</b><button aria-label="Close admin navigation" onClick={() => setMenu(false)} className="rounded-xl border border-[#29413A] p-2"><X size={18}/></button></div>{links}</div>}</div></main>
}
