"use client"
import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, Bell, CheckCircle2, Clock3, TrendingUp, WalletCards } from 'lucide-react'
import { BottomNav } from '@/components/layout/BottomNav'
import { Card } from '@/components/ui/card'
import { getTransactions } from '@/services/walletService'
import type { WalletTransaction } from '@/types/database'
import { getTradingOrders, getTradingPositions, type TradingOrder, type TradingPosition } from '@/services/internalTradingService'
export default function NotificationsPage(){const router=useRouter();const [tx,setTx]=useState<WalletTransaction[]>([]);const [orders,setOrders]=useState<TradingOrder[]>([]);const [positions,setPositions]=useState<TradingPosition[]>([]);const [systemNotifications,setSystemNotifications]=useState<any[]>([]);useEffect(()=>{void Promise.all([getTransactions(20),getTradingOrders(),getTradingPositions(),fetch('/api/notifications',{credentials:'same-origin'}).then(r=>r.ok?r.json():[]) ]).then(([a,b,c,n])=>{setTx(a);setOrders(b);setPositions(c);setSystemNotifications(Array.isArray(n)?n:[])}).catch(()=>{})},[]);const events=[...systemNotifications.map((x:any)=>({id:`n-${x.id}`,title:x.title,body:x.body,date:x.created_at,kind:'wallet'})),...tx.map(x=>({id:`tx-${x.id}`,title:x.title,body:`Wallet event · ${x.status}`,date:x.created_at,kind:'wallet'})),...orders.slice(0,10).map(x=>({id:`o-${x.id}`,title:`${x.mode==='spot'?'Spot':'Futures'} ${x.side} ${x.symbol}`,body:`${x.order_type} order · ${x.status}`,date:x.created_at,kind:'trade'})),...positions.slice(0,10).map(x=>({id:`p-${x.id}`,title:`Open ${x.mode} position · ${x.symbol}`,body:`${x.side} · ${x.quantity} units`,date:x.opened_at,kind:'position'}))].sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime());return <main className="min-h-screen bg-[#EEF2F1] pb-32 text-[#183A36]"><header className="sticky top-0 z-30 border-b border-[#D6E1DE] bg-[#EEF2F1]/95 p-4 backdrop-blur"><button onClick={()=>router.back()} className="h-10 w-10 rounded-xl bg-white border border-[#D6E1DE] flex items-center justify-center"><ArrowLeft size={18}/></button><div className="mt-4 flex items-center gap-2"><Bell className="text-[#087F5B]" size={20}/><div><h1 className="text-[22px] font-black">Notifications</h1><p className="text-[10px] text-[#708A85]">Account, deposit and trading events</p></div></div></header><div className="space-y-2 p-4">{events.map(e=><Card key={e.id} className="rounded-2xl border-[#D6E1DE] bg-white p-4 shadow-none"><div className="flex gap-3"><div className="h-9 w-9 shrink-0 rounded-xl bg-[#E8F7F0] text-[#087F5B] flex items-center justify-center">{e.kind==='wallet'?<WalletCards size={16}/>:e.kind==='trade'?<TrendingUp size={16}/>:<CheckCircle2 size={16}/>}</div><div className="min-w-0 flex-1"><p className="text-[11px] font-black">{e.title}</p><p className="mt-1 text-[9px] text-[#708A85]">{e.body}</p><p className="mt-2 text-[8px] text-[#9AA6A2]">{new Date(e.date).toLocaleString()}</p></div></div></Card>)}{!events.length&&<Card className="rounded-2xl border-[#D6E1DE] bg-white p-6 text-center"><Clock3 className="mx-auto text-[#087F5B]"/><p className="mt-3 text-[11px] font-black">No notifications yet</p><p className="mt-1 text-[9px] text-[#708A85]">Trade and account activity will appear here.</p></Card>}</div><BottomNav/></main>}
