"use client"

import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { ArrowUpRight, Search, SlidersHorizontal, X } from 'lucide-react'
import { browserTabManager, type BrowserTab } from '@/lib/browser-tab-manager'

const groups = [
  ['Top Browsers', 'Browse the web your way.', [['Google Chrome','Web Browser','google.com'],['Firefox','Privacy-focused Browser','firefox.com'],['Brave','Privacy & Web Browser','brave.com'],['Opera','Web Browser','opera.com'],['Opera Mini','Mobile Browser','opera.com'],['DuckDuckGo Browser','Private Browser','duckduckgo.com'],['Microsoft Edge','Web Browser','microsoft.com']]],
  ['Popular Exchanges', 'Access major digital-asset trading ecosystems.', [['Binance','Global Crypto Exchange','binance.com'],['Bybit','Crypto Trading Platform','bybit.com'],['OKX','Crypto Exchange & Web3','okx.com'],['Coinbase','Crypto Platform','coinbase.com'],['Kraken','Crypto Exchange','kraken.com'],['Bitget','Crypto Exchange & Trading','bitget.com']]],
  ['AI', 'Search, think, create and work with AI.', [['ChatGPT','AI assistant for writing, research and creation','chatgpt.com'],['Gemini','Google AI assistant and multimodal tools','gemini.google.com'],['Claude','AI assistant for analysis, writing and coding','claude.ai'],['Duck.ai','Private AI chat experience','duck.ai'],['Perplexity','AI-powered search and research','perplexity.ai'],['Microsoft Copilot','AI assistant across Microsoft products','copilot.microsoft.com']]],
  ['Social & X', 'Follow conversations, communities and market activity.', [['X','Social & Market Conversation','x.com'],['LinkedIn','Professional Network','linkedin.com'],['Reddit','Communities & Discussions','reddit.com'],['Instagram','Social & Visual Media','instagram.com'],['YouTube','Video & Creator Platform','youtube.com'],['Threads','Social Conversations','threads.net']]],
  ['Financial News', 'Markets, business, technology and global financial news.', [['Bloomberg','Business & Markets','bloomberg.com'],['Reuters','Global News & Markets','reuters.com'],['CNBC','Business & Markets','cnbc.com'],['Financial Times','Business & Finance','ft.com'],['The New York Times','Global News','nytimes.com'],['Wall Street Journal','Business & Finance','wsj.com'],['CoinDesk','Digital Assets & Crypto','coindesk.com'],['Yahoo Finance','Markets & Finance','finance.yahoo.com']]],
  ['Music & Audio', 'Music, podcasts and audio streaming.', [['Spotify','Music & Podcasts','spotify.com'],['Apple Music','Music Streaming','music.apple.com'],['YouTube Music','Music & Audio','music.youtube.com'],['SoundCloud','Independent Music & Audio','soundcloud.com'],['Deezer','Music Streaming','deezer.com'],['Audiomack','Music & Audio','audiomack.com']]],
  ['Finance & Markets', 'Market information, research and financial tools.', [['TradingView','Charts & Market Analysis','tradingview.com'],['CoinMarketCap','Crypto Markets & Data','coinmarketcap.com'],['Yahoo Finance','Markets & Financial Data','finance.yahoo.com'],['Investing.com','Markets & Economic Data','investing.com'],['Google Finance','Markets & Financial Information','google.com/finance'],['Stocktwits','Market Conversations','stocktwits.com']]],
  ['Developer & Technology', 'Build, research and work across the modern web.', [['GitHub','Code & Open Source','github.com'],['GitLab','DevSecOps & Software Development','gitlab.com'],['Stack Overflow','Developer Q&A','stackoverflow.com'],['npm','JavaScript Packages','npmjs.com'],['Vercel','Web Development & Deployment','vercel.com'],['Supabase','Postgres & Backend Platform','supabase.com'],['Docker','Containers & Development','docker.com'],['Cloudflare','Web Infrastructure & Security','cloudflare.com']]],
  ['Communication & Communities', 'Connect with people, teams and communities.', [['WhatsApp','Messaging & Calls','whatsapp.com'],['Telegram','Messaging & Communities','telegram.org'],['Discord','Communities & Voice','discord.com'],['Slack','Work Communication','slack.com'],['Zoom','Video Meetings','zoom.us'],['Google Meet','Video Meetings','meet.google.com']]],
  ['Productivity & Work', 'Tools for work, organization and collaboration.', [['Notion','Notes & Workspace','notion.so'],['Google Workspace','Work & Collaboration','workspace.google.com'],['Microsoft 365','Work & Productivity','microsoft.com'],['Trello','Project Organization','trello.com'],['Asana','Project Management','asana.com'],['Canva','Design & Visual Content','canva.com'],['Dropbox','Cloud Storage','dropbox.com'],['Google Drive','Cloud Storage & Collaboration','drive.google.com']]],
  ['Web3 & Onchain', 'Explore wallets, protocols and onchain ecosystems.', [['MetaMask','Wallet & Web3 Access','metamask.io'],['Coinbase Wallet','Self-Custody Wallet','wallet.coinbase.com'],['Phantom','Crypto Wallet','phantom.app'],['Trust Wallet','Crypto Wallet','trustwallet.com'],['WalletConnect','Wallet Connectivity','walletconnect.com'],['OpenSea','Digital Assets Marketplace','opensea.io'],['Uniswap','Decentralized Exchange','app.uniswap.org'],['Etherscan','Ethereum Block Explorer','etherscan.io']]],
  ['Search & Research', 'Find information across the web.', [['Google','Web Search','google.com'],['DuckDuckGo','Private Search','duckduckgo.com'],['Bing','Web Search','bing.com'],['Brave Search','Private Search','search.brave.com'],['Wikipedia','Open Knowledge','wikipedia.org'],['Perplexity','AI Search & Research','perplexity.ai']]],
] as const

export function EcosystemHub() {
  const [appSearch, setAppSearch] = useState('')
  const [webSearch, setWebSearch] = useState('')
  const [tabsOpen, setTabsOpen] = useState(false)
  const [tabs, setTabs] = useState<BrowserTab[]>([])
  useEffect(() => browserTabManager.subscribe(setTabs), [])
  const filtered = useMemo(() => appSearch.trim() ? groups.map(([name, subtitle, items]) => [name, subtitle, items.filter(([title, description]) => `${title} ${description}`.toLowerCase().includes(appSearch.toLowerCase()))] as const).filter(([, , items]) => items.length) : groups, [appSearch])
  const open = async (host: string) => browserTabManager.create(host.includes('/') ? `https://${host}` : `https://${host}`)
  const search = async (event: FormEvent) => { event.preventDefault(); const value = webSearch.trim(); if (!value) return; const url = /^https?:\/\//i.test(value) ? value : /^[\w-]+\.[\w.-]+/.test(value) ? `https://${value}` : `https://www.google.com/search?q=${encodeURIComponent(value)}`; await open(url); setWebSearch('') }
  return <section className="mb-8 rounded-[28px] border border-[#e7ddd8] bg-[#fbf7f5] p-4 shadow-sm sm:p-5">
    <div className="mb-4 flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#a07068]">NexMonie Extension</p><h2 className="mt-1 text-xl font-black tracking-tight text-[#342a28]">Your compact gateway to the web</h2></div><button onClick={() => setTabsOpen(!tabsOpen)} aria-label="Open browser tabs" className="relative flex size-9 items-center justify-center rounded-xl border border-[#decfca] bg-[#fffdfb] text-[#342a28]"><SlidersHorizontal size={16}/>{tabs.length > 0 && <span className="absolute -right-1 -top-1 flex size-4 items-center justify-center rounded-full bg-[#d86f68] text-[9px] font-black text-white">{tabs.length}</span>}</button></div>
    <form onSubmit={search} className="flex items-center gap-2 rounded-full border border-[#e5d9d5] bg-[#fffdfb] px-3 py-2.5 shadow-sm"><Search size={17} className="text-[#9b8580]"/><input value={webSearch} onChange={e => setWebSearch(e.target.value)} placeholder="Search Google or enter a web address" className="min-w-0 flex-1 bg-transparent text-[13px] text-[#342a28] outline-none placeholder:text-[#aa9892]"/><button className="rounded-full bg-[#342a28] px-3 py-1.5 text-[10px] font-black text-white">Search</button></form>
    <div className="mt-4 flex gap-2 overflow-x-auto pb-1">{groups.map(([name]) => <a key={name} href={`#${name.toLowerCase().replaceAll(' ','-').replaceAll('&','and')}`} className="whitespace-nowrap rounded-full border border-[#e4d7d2] bg-[#fffdfb] px-3 py-1.5 text-[10px] font-bold text-[#6f5c57]">{name.replace(' & ', ' + ')}</a>)}</div>
    {tabsOpen && <div className="mt-4 rounded-2xl border border-[#e4d7d2] bg-[#fffdfb] p-3"><div className="mb-2 flex items-center justify-between"><p className="text-[10px] font-black uppercase tracking-widest text-[#6f5c57]">Tabs</p><button onClick={() => browserTabManager.create()} className="text-[11px] font-black text-[#c76b64]">+ New tab</button></div>{tabs.length ? tabs.map(tab => <div key={tab.id} className={`flex items-center gap-2 border-t border-[#eee5e1] py-2 ${tab.active ? 'text-[#c76b64]' : 'text-[#342a28]'}`}><button onClick={() => browserTabManager.activate(tab.id)} className="min-w-0 flex-1 text-left"><p className="truncate text-[12px] font-bold">{tab.title}</p><p className="truncate text-[10px] text-[#9b8580]">{tab.domain}</p></button><button onClick={() => browserTabManager.close(tab.id)} aria-label={`Close ${tab.title}`}><X size={14}/></button></div>) : <p className="py-3 text-[11px] text-[#9b8580]">No tracked browser tabs yet.</p>}</div>}
    <div className="mt-6 space-y-6">{filtered.map(([name, subtitle, items]) => <div key={name} id={name.toLowerCase().replaceAll(' ','-').replaceAll('&','and')}><div className="mb-2"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#a07068]">{name}</p><p className="mt-1 text-[11px] text-[#806d67]">{subtitle}</p></div><div className="grid gap-2 sm:grid-cols-2">{items.map(([title, description, host]) => <button key={`${name}-${title}`} onClick={() => open(host)} className="group flex items-center gap-3 rounded-2xl border border-[#eadfdb] bg-[#fffdfb] p-3 text-left transition hover:border-[#d7aaa2] hover:bg-[#fffaf8]"><img src={`https://www.google.com/s2/favicons?domain=${host}&sz=64`} alt="" className="size-7 rounded-lg"/><span className="min-w-0 flex-1"><span className="block truncate text-[12px] font-black text-[#342a28]">{title}</span><span className="block truncate text-[10px] text-[#927d77]">{description}</span><span className="mt-0.5 block text-[9px] text-[#b09c96]">Platform access</span></span><ArrowUpRight size={15} className="text-[#c76b64] transition group-hover:translate-x-0.5"/></button>)}</div></div>)}</div>
    <div className="mt-6 flex items-center gap-2 border-t border-[#eadfdb] pt-4"><input value={appSearch} onChange={e => setAppSearch(e.target.value)} placeholder="Search NexMonie apps" className="min-w-0 flex-1 rounded-xl border border-[#e4d7d2] bg-[#fffdfb] px-3 py-2 text-[11px] outline-none"/><span className="text-[10px] text-[#9b8580]">Discovery links, not endorsements.</span></div>
  </section>
}
