"use client"

import { useEffect, useState } from "react"
import { ArrowLeft, ArrowRight, Check, Clock3, Copy, Landmark, Loader2, ShieldCheck } from "lucide-react"
import { useRouter } from "next/navigation"
import { BottomNav } from "@/components/layout/BottomNav"
import { NexLogo } from "@/components/ui/NexLogo"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { useToast } from "@/hooks/use-toast"
import { getDepositSession, submitDepositRequest, type DepositSession } from "@/services/deposit"

type Bank = { id: string; name: string; code?: string }

export default function DepositPage() {
  const router = useRouter(); const { toast } = useToast()
  const [session, setSession] = useState<DepositSession | null>(null); const [banks, setBanks] = useState<Bank[]>([])
  const [amount, setAmount] = useState(""); const [sourceBank, setSourceBank] = useState(""); const [accountName, setAccountName] = useState("")
  const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [submitted, setSubmitted] = useState(false); const [seconds, setSeconds] = useState(900)

  useEffect(() => { Promise.all([getDepositSession().then(setSession), fetch("/api/banks").then((response) => response.json()).then(setBanks)]).catch(() => toast({ variant: "destructive", title: "Deposit unavailable", description: "We could not load an active merchant account." })).finally(() => setLoading(false)) }, [toast])
  useEffect(() => { if (!session || submitted || seconds <= 0) return; const timer = window.setInterval(() => setSeconds((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer) }, [session, submitted, seconds])
  const copy = (value: string) => { void navigator.clipboard?.writeText(value); toast({ title: "Copied" }) }
  const validAmount = /^(?:\d+)(?:\.\d{1,2})?$/.test(amount) && Number(amount) > 0
  const submit = async () => { if (!session || !validAmount || !sourceBank || accountName.trim().length < 2) { toast({ variant: "destructive", title: "Complete the deposit details", description: "Enter your account name, sending bank and exact amount." }); return }; setSubmitting(true); try { await submitDepositRequest({ amount, senderBank: sourceBank, sourceAccountName: accountName, merchantAccountId: session.merchantAccountId }); setSubmitted(true) } catch (error) { toast({ variant: "destructive", title: "Deposit not recorded", description: error instanceof Error ? error.message : "Please try again." }) } finally { setSubmitting(false) } }
  const time = `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`

  return <main className="min-h-screen bg-[#f4efeb] pb-28 text-[#302825]"><header className="sticky top-0 z-20 border-b border-[#e5dad4] bg-[#f4efeb]/95 px-4 py-4 backdrop-blur"><div className="mx-auto flex max-w-2xl items-center justify-between"><button onClick={() => router.back()} aria-label="Go back" className="grid size-10 place-items-center rounded-xl border border-[#ded2cc] bg-[#fffdfa]"><ArrowLeft size={18}/></button><NexLogo/><span className="w-10"/></div></header><div className="mx-auto max-w-2xl px-4 py-6"><p className="text-[10px] font-black uppercase tracking-[.22em] text-[#9b7169]">Bank transfer</p><h1 className="mt-1 text-3xl font-black tracking-tight">Deposit</h1><p className="mt-2 max-w-lg text-sm leading-6 text-[#8f7c75]">Transfer NGN to the assigned merchant account. Your balance changes only after review.</p>
    {submitted ? <section className="mt-6 rounded-3xl border border-[#e5dad4] bg-[#fffdfa] p-6 text-center"><div className="mx-auto grid size-14 place-items-center rounded-full bg-[#f5ddd8] text-[#bd655c]"><Check/></div><h2 className="mt-4 text-xl font-black">Deposit submitted</h2><p className="mt-2 text-sm leading-6 text-[#8f7c75]">Your deposit is pending verification. It will remain pending until an authorized reviewer confirms the transfer.</p><button onClick={() => router.push("/transactions")} className="mt-5 inline-flex h-11 items-center gap-2 rounded-xl bg-[#302825] px-5 text-sm font-bold text-white">View activity <ArrowRight size={15}/></button></section> : <div className="mt-6 flex flex-col gap-4">
      <section className="rounded-3xl border border-[#e5dad4] bg-[#fffdfa] p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#9b7169]">Deposit method</p><h2 className="mt-1 text-lg font-black">Online bank transfer</h2></div><div className="grid size-11 place-items-center rounded-2xl bg-[#302825] text-white"><Landmark size={20}/></div></div><div className="mt-4 flex items-center gap-2 text-xs text-[#8f7c75]"><Clock3 size={14}/> Processing time: instant to 30 minutes <span className="ml-auto font-bold text-[#bd655c]">Fee 0%</span></div></section>
      <section className="rounded-3xl border border-[#e5dad4] bg-[#fffdfa] p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#9b7169]">Assigned merchant account</p><h2 className="mt-1 text-lg font-black">Transfer to this account</h2></div>{session && <span className="rounded-full bg-[#f5ddd8] px-3 py-1 text-[10px] font-black text-[#a34f48]">{time}</span>}</div>{loading ? <div className="flex items-center gap-2 py-8 text-sm text-[#8f7c75]"><Loader2 className="animate-spin" size={16}/> Loading active account…</div> : session ? <div className="mt-5 grid gap-4 rounded-2xl bg-[#f6f0ec] p-4"><Detail label="Bank" value={session.bankName}/><Detail label="Account name" value={session.accountName} copy={() => copy(session.accountName)}/><Detail label="Account number" value={session.accountNumber} copy={() => copy(session.accountNumber)} large/></div> : <p className="mt-4 rounded-2xl bg-[#fbebe8] p-4 text-sm text-[#9d4d45]">No active merchant account is available right now. Please try again later.</p>}<div className="mt-4 flex items-start gap-2 text-xs leading-5 text-[#8f7c75]"><ShieldCheck size={15} className="mt-0.5 shrink-0 text-[#bd655c]"/>Use the exact account details above. Keep your transfer receipt for reconciliation.</div></section>
      <section className="rounded-3xl border border-[#e5dad4] bg-[#fffdfa] p-5"><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#9b7169]">Your transfer details</p><div className="mt-4 flex flex-col gap-4"><label className="text-sm font-bold">Account name<input value={accountName} onChange={(event) => setAccountName(event.target.value)} placeholder="Name on the sending bank account" className="mt-2 h-12 w-full rounded-xl border border-[#ded2cc] bg-[#fffdfa] px-3 text-sm font-normal outline-none focus:border-[#bd655c]"/></label><label className="text-sm font-bold">Bank used to send funds<Select value={sourceBank} onValueChange={setSourceBank}><SelectTrigger className="mt-2 h-12 rounded-xl border-[#ded2cc] bg-[#fffdfa] font-normal"><SelectValue placeholder="Select your bank"/></SelectTrigger><SelectContent>{banks.map((bank) => <SelectItem key={bank.id} value={bank.name}>{bank.name}</SelectItem>)}</SelectContent></Select></label><label className="text-sm font-bold">Amount<input inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value.replace(/[^0-9.]/g, ""))} placeholder="0.00" className="mt-2 h-14 w-full rounded-xl border border-[#ded2cc] bg-[#fffdfa] px-3 text-2xl font-black outline-none focus:border-[#bd655c]"/><span className="mt-1 block text-xs font-normal text-[#8f7c75]">NGN • exact amount including kobo</span></label></div><button disabled={submitting || !session || seconds === 0} onClick={submit} className="mt-5 flex h-13 w-full items-center justify-center gap-2 rounded-xl bg-[#302825] text-sm font-black text-white disabled:cursor-not-allowed disabled:opacity-45">{submitting ? <Loader2 className="animate-spin" size={17}/> : <>I&apos;ve made the transfer <ArrowRight size={17}/></>}</button></section>
    </div>}
    </div><BottomNav/></main>
}

function Detail({ label, value, copy, large }: { label: string; value: string; copy?: () => void; large?: boolean }) { return <div><p className="text-[10px] uppercase tracking-[.16em] text-[#8f7c75]">{label}</p><div className="mt-1 flex items-center justify-between gap-3"><p className={large ? "text-2xl font-black tracking-wide" : "text-sm font-black"}>{value}</p>{copy && <button onClick={copy} aria-label={`Copy ${label}`} className="grid size-9 shrink-0 place-items-center rounded-xl bg-[#fffdfa]"><Copy size={15}/></button>}</div></div> }
