'use client'
import { useState } from 'react'
export function WalletControls({userId,currency='USDT',onDone}:{userId:string,currency?:string,onDone?:()=>void}){
 const [busy,setBusy]=useState(false); const [message,setMessage]=useState('')
 const run=async(action:'freeze'|'unfreeze'|'restrict_withdrawals'|'allow_withdrawals'|'restrict_trading'|'allow_trading'|'reconcile')=>{
  setBusy(true);setMessage('')
  try{const r=await fetch('/api/admin/wallet-controls',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId,currency,action,reason:action.includes('restrict')||action==='freeze'?window.prompt('Reason')||undefined:undefined})});const j=await r.json();if(!r.ok)throw new Error(j?.error||'Wallet operation failed');setMessage(j.status||'Done');onDone?.()}catch(e){setMessage(e instanceof Error?e.message:'Wallet operation failed')}finally{setBusy(false)}
 }
 return <div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><button disabled={busy} onClick={()=>void run('freeze')} className="rounded-lg border border-[#713B3B] px-2 py-2 text-[10px] font-bold text-[#FFB4B4]">Freeze</button><button disabled={busy} onClick={()=>void run('unfreeze')} className="rounded-lg border border-[#29413A] px-2 py-2 text-[10px] font-bold">Unfreeze</button><button disabled={busy} onClick={()=>void run('restrict_withdrawals')} className="rounded-lg border border-[#29413A] px-2 py-2 text-[10px] font-bold">Block withdrawals</button><button disabled={busy} onClick={()=>void run('restrict_trading')} className="rounded-lg border border-[#29413A] px-2 py-2 text-[10px] font-bold">Block trading</button><button disabled={busy} onClick={()=>void run('allow_withdrawals')} className="rounded-lg border border-[#29413A] px-2 py-2 text-[10px] font-bold">Allow withdrawals</button><button disabled={busy} onClick={()=>void run('allow_trading')} className="rounded-lg border border-[#29413A] px-2 py-2 text-[10px] font-bold">Allow trading</button><button disabled={busy} onClick={()=>void run('reconcile')} className="rounded-lg bg-[#55D6A7] px-2 py-2 text-[10px] font-black text-[#10231F] sm:col-span-2">Reconcile wallet</button>{message&&<span className="col-span-full text-[10px] text-[#8DE0BD]">{message}</span>}</div>
}
